/Users/hxs/Documents/MATLAB
/Users/hxs/Documents
/Users/hxs/Documents/Study/Research
/Users/hxs/Documents/Study/Research/EEG-fMRI_Resting/Data/dq041813/eeg
/Users/hxs/Documents/Study/Research/EEG-fMRI_Resting/Data/dq041813
/Users/hxs/Documents/Study/Research/EEG-fMRI_Resting/Data
/Users/hxs/Documents/Study/Research/EEG-fMRI_Resting/Data/ghg040613/eeg
/Users/hxs/Documents/Study/Research/EEG-fMRI_Resting
/Users/hxs/Documents/Study/Research/EEG-fMRI_Resting/Data/xh032013/raw
/Users/hxs/Documents/Study/Research/EEG-fMRI_Resting/Data/xh032013
/Users/hxs/Documents/Study/Research/EEG-fMRI_Resting/Data/xh032013/eeg
/Users/hxs/Documents/Study/Research/EEG-fMRI_Resting/Data/xh030313
/Users/hxs/Documents/Study/Research/EEG-fMRI_Resting/Data/xh060713
/Users/hxs/Documents/Study/Research/EEG-fMRI_Resting/Data/xh030313/eeg
/Users/hxs/Documents/Study/Research/EEG-fMRI_Resting/REST/FunImg/xh030313
/Users/hxs/Documents/Study/Research/EEG-fMRI_Resting/REST/FunImg
/Users/hxs/Documents/Study/Research/EEG-fMRI_Resting/REST
/Users/hxs/Documents/Study/Research/EEG-fMRI_Resting/REST/FunImgA
/Users/hxs/Documents/Study/Research/EEG-fMRI_Resting/Data/xh030313/raw
/Users/hxs/Documents/Study/Research/EEG-fMRI_Resting/REST/FunImg/dq041813_2
