/Users/hxs/Documents/MATLAB
/Users/hxs/Documents/Study/Research/Analysis/hxs_matlab
/Users/hxs/Documents/Study/Research/Analysis
/Users/hxs/Documents
/Users/hxs/Documents/Study/Research/Analysis/gary/fmriutil
/Users/hxs/Documents/Study/Research/Analysis/gary
/Users/hxs/Documents/Study/Research/Analysis/gary/brain
/Users/hxs/Documents/Study/Research
/Users/hxs/Documents/Study
/Users/hxs/Documents/Study/Research/EEG-fMRI_Resting
/Users/hxs/Downloads
/Users/hxs
/Users/hxs/Documents/Study/Research/EEG-fMRI_Resting/REST/FunImgARCWS/xh032013
/Users/hxs/Documents/Study/Research/EEG-fMRI_Resting/REST/FunImgARCWS
/Users/hxs/Documents/Study/Research/EEG-fMRI_Resting/REST
/Users/hxs/Documents/Study/Research/EEG-fMRI_Resting/Data
/Users/hxs/Documents/MATLAB/eeglab/external/fieldtrip-partial/forward/private
/Users/hxs/Documents/MATLAB/fcnFirstOrderStatisticsFilter
/Users/hxs/Desktop
/Users/hxs/Documents/Study/Research/EEG-fMRI_Resting/REST/FunImgARCWS/ql041913_2
