/Users/hxs/Research/Analysis/hxs_matlab/Stimulus
/Users/hxs/Research/Analysis/hxs_matlab
/Users/hxs/Research/Analysis
/Users/hxs/Research
/Users/hxs/Research/Resample
/Users/hxs/Documents/MATLAB
/Users/hxs/Research/Face_EEG_fMRI
/Users/hxs/Research/freesurfer
/Users/hxs
/Users/hxs/Documents/MATLAB/export_fig
/Users/hxs/Documents
/Users/hxs/Research/EEG-fMRI_BCG/Data/ghg082713/eeg
/Users/hxs/Research/EEG-fMRI_BCG/Data/ghg082713
/Users/hxs/Research/EEG-fMRI_BCG/Data
/Users/hxs/Research/EEG-fMRI_BCG
/Users/hxs/Downloads
/Users/hxs/Documents/MATLAB/robust CCA
/Users/hxs/Documents/MATLAB/robust_cca
/Users/hxs/Documents/MATLAB/LIBRA_31okt11
/Users/hxs/Research/Face_EEG_fMRI/EEG_ERP_ALL
