/Users/hxs/Documents/MATLAB
/Users/hxs/Documents/MATLAB/LIBRA_31okt11
/Users/hxs/Research/Face_EEG_fMRI/EEG_ERP_ALL
/Users/hxs/Research/Face_EEG_fMRI
/Users/hxs/Research
/Users/hxs
/Users/hxs/Documents
/Users/hxs/dotfiles
/Users/hxs/Research/EEG-fMRI_BCG
/Users/hxs/Dropbox/Neuracle/Develop/EEG Test
/Users/hxs/Dropbox/Neuracle/Develop
/Users/hxs/Dropbox/Neuracle/Develop/Emulator/SerialDataParser
/Users/hxs/Dropbox/Neuracle/Develop/Emulator
/Users/hxs/Dropbox/Neuracle
/Users/hxs/Dropbox
/Users/hxs/Research/Analysis/hxs_matlab
/Users/hxs/Research/Analysis
/Users/hxs/Research/EEG-fMRI_BCG/Data/ghg082713/eeg
/Users/hxs/Documents/Study/Research/Analysis/hxs_matlab
/Users/hxs/Documents/Study/Research/Analysis
