/Users/hxs/Documents/Study/Research/Analysis/hxs_matlab/Stimulus
/Users/hxs/Downloads/inputsdlg_v2.0.4
/Users/hxs/Downloads
/Users/hxs
/Users/hxs/Documents/MATLAB
/Users/hxs/Documents
/Users/hxs/Documents/Study/Research/Analysis/hxs_matlab/Stimulus/Scene/neutral
/Users/hxs/Documents/Study/Research/Analysis/hxs_matlab/Stimulus/Scene
/Users/hxs/Documents/Study/Research/Analysis/hxs_matlab
/Users/hxs/Documents/Study/Research/Analysis
/Users/hxs/Documents/Study/Research
/Users/hxs/Documents/Study
/Users/hxs/Research/Analysis/hxs_matlab/Stimulus
/Users/hxs/Research/Analysis/hxs_matlab
/Users/hxs/Research/Analysis
/Users/hxs/Research
/Users/hxs/Research/Resample
/Users/hxs/Research/Face_EEG_fMRI
/Users/hxs/Research/freesurfer
/Users/hxs/Documents/MATLAB/export_fig
