/Users/hxs/Documents/Study/Research/Analysis/hxs_matlab/Stimulus
/Users/hxs/Documents/MATLAB
/Users/hxs/Documents/Study/Research/Analysis/hxs_matlab
/Users/hxs/Documents/Study/Research/Analysis
/Users/hxs/Documents/Study/Research
/Users/hxs/Documents/Study
/Users/hxs/Documents
/Users/hxs
/Users/hxs/Research/Analysis/hxs_matlab/Stimulus
/Users/hxs/Research/Analysis/hxs_matlab
/Users/hxs/Research/Analysis
/Users/hxs/Research
/Users/hxs/Research/Resample
/Users/hxs/Research/Face_EEG_fMRI
/Users/hxs/Research/freesurfer
/Users/hxs/Documents/MATLAB/export_fig
/Users/hxs/Research/EEG-fMRI_BCG/Data/ghg082713/eeg
/Users/hxs/Research/EEG-fMRI_BCG/Data/ghg082713
/Users/hxs/Research/EEG-fMRI_BCG/Data
/Users/hxs/Research/EEG-fMRI_BCG
